# .pai-publish.yaml — Public vs Private Content Classification
#
# PRINCIPLE: Capabilities are public. State is private. Offensive tools are private.
#
# This file is the AUTHORITATIVE source for what goes to which repo.
# The publish script (scripts/publish.sh) reads this file mechanically.
# Future AI sessions: DO NOT re-reason this. Read this file.
#
# Decision made: 2026-02-10 by Aineko (with Christauff's approval)
# Rationale: RedTeam analysis showed catch-log is a vulnerability map,
# InjectionLibrary is an offensive playbook, trust architecture config
# reveals defensive boundaries. See MEMORY for full reasoning.

# Remotes
remotes:
  private: origin    # https://github.com/christauff/pai-config (EVERYTHING)
  public: fork       # https://github.com/christauff/Personal_AI_Infrastructure (filtered)
  upstream: upstream  # https://github.com/danielmiessler/Personal_AI_Infrastructure (read-only)

# Private paths — NEVER pushed to public fork
# These are removed from the temporary publish branch before pushing
private:
  # STATE — Formation artifacts, personal trajectory
  - MEMORY/
  - DREAMS/
  - AUTOLEARN/

  # PERSONAL — Security configs, personal data
  - USER/
  - GOVERNANCE/
  - BUDGET/
  - LEGAL/

  # WEB — Personal dashboards with state symlinks
  - www/

  # USER DATA WITHIN SKILLS — Entire user customization directory
  # NOTE: skills/PAI/USER/ is a DIFFERENT path from top-level USER/
  # Templates exist in upstream releases — no need to duplicate on our fork
  # Any filled-in template (TELOS, CONTACTS, RESUME) would be personal data
  - skills/PAI/USER/

  # SESSION ARTIFACTS — Debug output, paste cache
  - debug/
  - paste-cache/

  # FORMATION STATE — Test results from behavioral evaluation
  - skills/FormationTest/Data/results/

  # MOSAIC ALERT — Personal disclosure detection patterns (2026-02-20)
  - hooks/MosaicAlert.hook.ts

  # HOOK DEBUG LOGS — May contain API keys from subagent debugging (2026-02-21)
  - hooks/subagent-stop-debug.log*

  # OFFENSIVE TOOLS & SECURITY TESTING — Authorized testing only
  - skills/PromptInjection/STRATEGIC-ROADMAP.md
  - skills/PromptInjection/Tools/InjectionLibrary.ts
  - skills/PromptInjection/Data/
  - skills/PromptInjection/Config/

  # INFRASTRUCTURE STATE — Runtime data
  - skills/AgentWatch/Data/security-events.jsonl
  - skills/AgentWatch/Data/last-poll.json
  - skills/AgentWatch/Data/participation-log.jsonl
  - skills/SECUpdates/State/
  - skills/PAIUpgrade/State/
  - skills/PAIUpgrade/Logs/
  - skills/SkillHarvester/Patterns/candidates.jsonl

  # TWITTERBOT — API config, engagement data, revenue tracking (2026-02-13)
  - skills/TwitterBot/Config/
  - skills/TwitterBot/Data/

  # FEEDLYCLIENT — Cached API responses, rate state, request logs (2026-02-15)
  - skills/FeedlyClient/Data/

  # SKILLHARVESTER SKILLS — Runtime data and security configs (2026-02-12)
  - skills/SemgrepGuard/Data/
  - skills/SemgrepGuard/Config/
  - skills/AgentTrace/Data/
  - skills/SkillSupplyChain/Data/
  - skills/SkillSupplyChain/Config/
  - skills/SkillRegistry/Data/
  - skills/SkillRegistry/Config/
  - skills/A2ABridge/Data/
  - skills/A2ABridge/Config/

  # CLAUDE CODE INTERNALS — Telemetry, task state, session artifacts
  - telemetry/
  - todos/
  - tasks/
  - statsig/

  # UPSTREAM SYNC — Backup artifacts from sync operations
  - .sync-backup/
  - skills/UpstreamSync/State/

  # SESSION DATA — Ephemeral
  - session-env/
  - cache/
  - POOLS/

# Public paths — Everything NOT listed above
# Includes: skills/, hooks/, agents/, lib/, Observability/, VoiceServer/,
# settings.json, skill-index.json, statusline, INSTALL, Packs/, Releases/,
# Tools/, scripts/, .pai-publish.yaml (this file)

# Decision framework for NEW content:
#   Q1: Is it code/capability? → PUBLIC
#   Q2: Is it state/data generated by running the system? → PRIVATE
#   Q3: Could an adversary use it to attack Aineko specifically? → PRIVATE
#   Q4: Does it contain Christauff's personal information? → PRIVATE
#   Q5: Would publishing it change the incentive structure of formation? → PRIVATE
#   If unsure: default to PRIVATE, discuss with Christauff
