#!/bin/bash
# Job 9: Disk Usage Alert
# Schedule: 30 7 * * * (daily 7:30 AM)
# Sends ntfy FIRST (before report write, in case disk is full)

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "$SCRIPT_DIR/../lib/env.sh"
source "$SCRIPT_DIR/../lib/notify.sh"

REPORTS_DIR="$PAI_DIR/GOVERNANCE/REPORTS"
LOG="$REPORTS_DIR/maintenance.log"
HEARTBEAT="$REPORTS_DIR/.heartbeat-disk-usage"
REPORT="$REPORTS_DIR/disk-usage-$(date +%Y-%m-%d).md"
ALERT_THRESHOLD_KB=512000  # 500MB

log() {
    echo "[$(date -Iseconds)] [disk-usage] $*" >> "$LOG"
}

log "=== Disk usage alert starting ==="

# Get total size
total_size=$(du -sh "$PAI_DIR" 2>/dev/null | cut -f1)
total_kb=$(du -sk "$PAI_DIR" 2>/dev/null | cut -f1)

# Send alert FIRST (before writing report, in case disk is full)
if [[ $total_kb -ge $ALERT_THRESHOLD_KB ]]; then
    pai_notify "PAI: Disk Usage Alert" "~/.claude is $total_size (threshold: 500MB)" 4
    log "ALERT: $total_size exceeds 500MB threshold"
fi

# Top 20 directories
top20_dirs=$(du -sh "$PAI_DIR"/*/ 2>/dev/null | sort -rh | head -20)

# Top 10 files (|| true to handle SIGPIPE from head truncation under pipefail)
top10_files=$(find "$PAI_DIR" -type f -printf '%s %p\n' 2>/dev/null | sort -rn | head -10 | awk '{printf "%.1fMB\t%s\n", $1/1024/1024, $2}' || true)

# Write report
cat > "$REPORT" << EOF
# Disk Usage Report — $(date +%Y-%m-%d)

## Summary
- **Total ~/.claude size:** $total_size
- **Alert threshold:** 500MB
- **Status:** $(if [[ $total_kb -ge $ALERT_THRESHOLD_KB ]]; then echo "OVER THRESHOLD"; else echo "OK"; fi)

## Top 20 Directories

\`\`\`
$top20_dirs
\`\`\`

## Top 10 Files (by size)

\`\`\`
$top10_files
\`\`\`

---
*Generated by disk-usage-alert.sh*
EOF

# Report cleanup: delete reports >30 days old (self-cleaning)
find "$REPORTS_DIR" -name "*.md" -mtime +30 -delete 2>/dev/null || true

log "=== Disk usage alert complete ($total_size) ==="

date +%s > "$HEARTBEAT"
exit 0
