#!/bin/bash
# Job 13: UpstreamSync Weekly Version Check
# Schedule: 0 7 * * 0 (weekly Sunday 7 AM)
# Detects new upstream PAI releases, writes alert file for MorningBrief
# Zero LLM cost — pure git operations on local repo

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "$SCRIPT_DIR/../lib/env.sh"
source "$SCRIPT_DIR/../lib/notify.sh"

REPORTS_DIR="$PAI_DIR/GOVERNANCE/REPORTS"
LOG="$REPORTS_DIR/maintenance.log"
HEARTBEAT="$REPORTS_DIR/.heartbeat-upstream-sync"
SYNC_STATE_DIR="$PAI_DIR/skills/UpstreamSync/State"
ALERT_FILE="$SYNC_STATE_DIR/upstream-alert-$(date +%Y-%m-%d).md"

log() {
    echo "[$(date -Iseconds)] [upstream-sync] $*" >> "$LOG"
}

log "=== UpstreamSync weekly check starting ==="

# Verify we're in a git repo
if ! git -C "$PAI_DIR" rev-parse --is-inside-work-tree &>/dev/null; then
    log "[ERROR] $PAI_DIR is not a git repository"
    exit 1
fi

# Verify UpstreamSync tool exists
SYNC_TOOL="$PAI_DIR/skills/UpstreamSync/Tools/UpstreamSync.ts"
if [[ ! -f "$SYNC_TOOL" ]]; then
    log "[ERROR] UpstreamSync.ts not found at $SYNC_TOOL"
    exit 1
fi

mkdir -p "$SYNC_STATE_DIR"

# Fetch upstream (git-state-check.sh runs at 8 AM Sunday, we run at 7 AM — fetch here too)
log "Fetching upstream..."
if ! timeout 30 git -C "$PAI_DIR" fetch upstream 2>>"$LOG"; then
    # upstream remote might not exist — try origin
    if ! timeout 30 git -C "$PAI_DIR" fetch origin 2>>"$LOG"; then
        log "[WARN] Could not fetch any remote"
    fi
fi

# Run UpstreamSync detect
log "Running UpstreamSync detect..."
if DETECT_OUTPUT=$(timeout 60 bun run "$SYNC_TOOL" detect --json 2>>"$LOG"); then
    DETECT_SIZE=${#DETECT_OUTPUT}
    log "Detect output: $DETECT_SIZE chars"

    # Write raw output to state dir
    echo "$DETECT_OUTPUT" > "$SYNC_STATE_DIR/last-detect.json"

    # Check if there are new versions (look for "new" or version strings in output)
    if echo "$DETECT_OUTPUT" | grep -qi '"new"\|"available"\|"unsynced"'; then
        log "[ALERT] New upstream version(s) detected"

        # Write alert file for MorningBrief
        cat > "$ALERT_FILE" << EOF
# Upstream PAI Version Alert

**Date:** $(date '+%Y-%m-%d %H:%M:%S')
**Source:** UpstreamSync weekly check

## Detection Output

\`\`\`
$DETECT_OUTPUT
\`\`\`

## Action Required

Run \`/UpstreamSync\` to review and selectively sync changes.

---
*Generated by upstream-sync-check.sh*
EOF
        log "Alert written to $ALERT_FILE"
        pai_notify "PAI: New Upstream Version" "New PAI release detected. Run /UpstreamSync to review." 3
    else
        log "No new upstream versions detected"
    fi
else
    EXIT_CODE=$?
    log "[WARN] UpstreamSync detect failed (exit $EXIT_CODE)"
fi

# Also run a quick diff summary if detect found something
if [[ -f "$ALERT_FILE" ]]; then
    log "Running UpstreamSync diff for summary..."
    if DIFF_OUTPUT=$(timeout 60 bun run "$SYNC_TOOL" diff 2>>"$LOG"); then
        DIFF_SIZE=${#DIFF_OUTPUT}
        if [[ $DIFF_SIZE -gt 50 ]]; then
            echo "$DIFF_OUTPUT" > "$SYNC_STATE_DIR/last-diff.txt"
            log "Diff summary written ($DIFF_SIZE chars)"
        fi
    fi
fi

# Cleanup: delete alert files >30 days old
find "$SYNC_STATE_DIR" -name "upstream-alert-*.md" -mtime +30 -delete 2>/dev/null || true

log "=== UpstreamSync weekly check complete ==="

date +%s > "$HEARTBEAT"
exit 0
